import React, { createContext, useContext, useState } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Nav
    "nav.about": "About",
    "nav.program": "Program",
    "nav.benefits": "Benefits",
    "nav.eligibility": "Eligibility",
    "nav.timeline": "Timeline",
    "nav.partners": "Partners",
    "nav.apply": "Apply Now",

    // Hero
    "hero.title": "Future Enabled Tech Careers for Women",
    "hero.subtitle": "A career-transition and digital upskilling initiative supporting women in Geneva to enter Switzerland's growing tech sector — practicing and developing concrete skills to become independent in the digital world.",
    "hero.cta1": "Apply Now",
    "hero.cta2": "Learn More",

    // About
    "about.tag": "About the Program",
    "about.title": "Enabling Sustainable Career Futures",
    "about.description": "Ellatech is a career-transition and digital upskilling initiative designed to support women in Geneva who aim to enter Switzerland's growing tech sector — practicing and developing concrete skills so they can become independent in the digital world.",
    "about.mission.title": "Our Mission",
    "about.mission.text": "Despite Switzerland's strong digital economy, many qualified women with international backgrounds face structural barriers to accessing IT careers. We address this gap through accessible digital training combined with employability preparation.",
    "about.who.title": "Who It's For",
    "about.who.text": "Women living in Geneva who want to transition into tech careers. No prior tech experience required — just motivation and basic digital access.",
    "about.gain.title": "What You'll Gain",
    "about.gain.text": "Market-relevant digital skills, professional mentorship, career guidance tailored to Swiss hiring standards, and access to Geneva's thriving tech ecosystem.",

    // Program
    "program.tag": "Program Overview",
    "program.title": "Your 3-Month Pathway to Tech",
    "program.month1.title": "Month 1",
    "program.month1.name": "Digital Foundations",
    "program.month1.desc": "Build your digital literacy, explore tech career paths, and receive your personalized AI skill assessment to guide your learning journey.",
    "program.month2.title": "Month 2",
    "program.month2.name": "Technical Skills",
    "program.month2.desc": "Dive into hands-on training in Web & Mobile Development, Data Analysis, or AI & Digital Skills based on your interests and assessment results.",
    "program.month3.title": "Month 3",
    "program.month3.name": "Career Preparation",
    "program.month3.desc": "Polish your CV, build your portfolio, practice interviews, and connect with Swiss tech employers through our partner network.",

    // Benefits
    "benefits.tag": "What Participants Receive",
    "benefits.title": "Everything You Need to Succeed",
    "benefits.ai": "AI Skill Assessment",
    "benefits.ai.desc": "Personalized evaluation of your skills, interests, and readiness to create a tailored learning pathway.",
    "benefits.training": "Structured Training",
    "benefits.training.desc": "12 weeks of guided, hands-on learning in high-demand digital fields with real-world projects.",
    "benefits.mentorship": "Mentorship Program",
    "benefits.mentorship.desc": "Connect with experienced women in tech who will guide and support your career transition.",
    "benefits.career": "Career Guidance",
    "benefits.career.desc": "CV building, interview prep, and job search strategies tailored to the Swiss market.",
    "benefits.ecosystem": "Tech Ecosystem Access",
    "benefits.ecosystem.desc": "Introductions to Swiss tech companies, networking events, and internship opportunities.",
    "benefits.community": "Peer Community",
    "benefits.community.desc": "Join a supportive community of women on the same journey — learn, grow, and succeed together.",

    // Eligibility
    "eligibility.tag": "Eligibility Criteria",
    "eligibility.title": "Who Can Apply?",
    "eligibility.subtitle": "Our program is designed for women who meet the following criteria:",
    "eligibility.1": "Live in the Canton of Geneva",
    "eligibility.2": "Identify as a woman",
    "eligibility.3": "Be passionate about transitioning into a tech career",
    "eligibility.4": "Have basic digital access (laptop & internet)",
    "eligibility.5": "Be motivated to pursue a career in tech",
    "eligibility.cta": "Check Your Eligibility & Apply",

    // Timeline
    "timeline.tag": "Program Timeline",
    "timeline.title": "Key Dates",
    "timeline.1.date": "June 2026",
    "timeline.1.title": "Applications Open",
    "timeline.1.desc": "Submit your application and complete the initial assessment.",
    "timeline.2.date": "September 2026",
    "timeline.2.title": "Cohort Starts",
    "timeline.2.desc": "Onboarding, orientation, and AI skill assessment.",
    "timeline.3.date": "September – November 2026",
    "timeline.3.title": "Program Duration",
    "timeline.3.desc": "12 weeks of intensive training and career preparation.",
    "timeline.4.date": "November 2026",
    "timeline.4.title": "Graduation & Career Launch",
    "timeline.4.desc": "Showcase projects, connect with employers, and launch your career.",

    // Partners
    "partners.tag": "Partners & Supporters",
    "partners.title": "Building Together",
    "partners.subtitle": "Ellatech is made possible through partnerships with local organizations, tech companies, and training institutions committed to inclusion and diversity.",
    "partners.ngos": "Local NGOs",
    "partners.ngos.desc": "Community organizations supporting integration and social inclusion in Geneva.",
    "partners.tech": "Tech Companies",
    "partners.tech.desc": "Leading Swiss tech firms providing mentorship, internships, and career pathways.",
    "partners.training": "Training Partners",
    "partners.training.desc": "Educational institutions offering curriculum support and certification.",
    "partners.cta": "Become a Partner",

    // Partner Form Page
    "partner.back": "Back to Partners",
    "partner.tag": "Partnership",
    "partner.title": "Become a Partner",
    "partner.subtitle": "Join us in empowering women in Geneva to build sustainable tech careers. Whether you're a company, NGO, or local association, your support makes a difference.",
    "partner.form.orgInfo": "Organization Information",
    "partner.form.orgName": "Organization Name",
    "partner.form.orgNamePlaceholder": "Your organization name",
    "partner.form.website": "Website",
    "partner.form.orgType": "Organization Type",
    "partner.form.orgType.company": "Company",
    "partner.form.orgType.ngo": "NGO",
    "partner.form.orgType.association": "Association",
    "partner.form.orgType.academic": "Academic",
    "partner.form.orgType.government": "Government",
    "partner.form.orgType.other": "Other",
    "partner.form.contactInfo": "Contact Person",
    "partner.form.contactName": "Full Name",
    "partner.form.contactNamePlaceholder": "Contact person's name",
    "partner.form.contactRole": "Role / Position",
    "partner.form.contactRolePlaceholder": "e.g. HR Manager",
    "partner.form.email": "Email",
    "partner.form.emailPlaceholder": "contact@organization.ch",
    "partner.form.phone": "Phone",
    "partner.form.partnershipInterest": "Partnership Interest",
    "partner.form.partnershipType": "How would you like to contribute?",
    "partner.form.type.mentorship": "Mentorship",
    "partner.form.type.internship": "Internships",
    "partner.form.type.training": "Training Support",
    "partner.form.type.funding": "Funding / Sponsorship",
    "partner.form.message": "Additional Message",
    "partner.form.messagePlaceholder": "Tell us more about your organization and how you'd like to collaborate...",
    "partner.form.terms": "I agree to be contacted by Ellatech regarding this partnership inquiry.",
    "partner.form.submit": "Submit Partnership Inquiry",
    "partner.form.submitting": "Submitting...",
    "partner.form.success": "Inquiry Submitted!",
    "partner.form.successDesc": "Thank you for your interest. We'll be in touch soon.",

    // Footer
    "footer.tagline": "We don't only train. We enable sustainable career futures.",
    "footer.program": "Program",
    "footer.connect": "Connect",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.rights": "All rights reserved.",

    // Apply Now Page
    "apply.back": "Back to Home",
    "apply.tag": "Application",
    "apply.title": "Apply to the Program",
    "apply.subtitle": "Take the first step toward your tech career. Fill out the form below and we'll get back to you.",
    "apply.form.personalInfo": "Personal Information",
    "apply.form.fullName": "Full Name",
    "apply.form.fullNamePlaceholder": "Your full name",
    "apply.form.email": "Email",
    "apply.form.emailPlaceholder": "your.email@example.com",
    "apply.form.phone": "Phone",
    "apply.form.nationality": "Nationality",
    "apply.form.nationalityPlaceholder": "e.g. Syrian, Eritrean, Colombian",
    "apply.form.residenceStatus": "Residence Status in Switzerland",
    "apply.form.residenceStatusPlaceholder": "e.g. Permit B, Permit F, Asylum seeker",
    "apply.form.background": "Background & Experience",
    "apply.form.education": "Education Level",
    "apply.form.education.high_school": "High School",
    "apply.form.education.bachelor": "Bachelor's Degree",
    "apply.form.education.master": "Master's or Higher",
    "apply.form.education.other": "Other",
    "apply.form.experience": "Previous Work Experience",
    "apply.form.experiencePlaceholder": "Briefly describe your work experience, if any...",
    "apply.form.techInterest": "Your Interest in Tech",
    "apply.form.techTrack": "Which track interests you most?",
    "apply.form.tech.webdev": "Web & App Development",
    "apply.form.tech.data": "Data Analysis",
    "apply.form.tech.ai": "AI & Digital Skills",
    "apply.form.tech.unsure": "Not Sure Yet",
    "apply.form.motivation": "Why do you want to join?",
    "apply.form.motivationPlaceholder": "Tell us about your goals and why this program is right for you...",
    "apply.form.terms": "I confirm that I meet the eligibility criteria and agree to be contacted by Ellatech.",
    "apply.form.submit": "Submit Application",
    "apply.form.submitting": "Submitting...",
    "apply.form.success": "Application Submitted!",
    "apply.form.successDesc": "Thank you for applying. We'll review your application and get back to you soon.",

    // Impact
    "impact.title": "Our Impact",
    "impact.members": "Participants",
    "impact.mentors": "Mentors",
    "impact.events": "Events",
    "impact.partners": "Partners",

    // About Page
    "aboutPage.tag": "About Ellatech",
    "aboutPage.title": "Empowering Women Into Tech Careers",
    "aboutPage.subtitle": "A digital career transition hub supporting women in Geneva to enter the technology sector.",
    "aboutPage.overview.title": "Overview",
    "aboutPage.overview.text": "Ellatech is a career-transition and digital upskilling initiative designed to support women in Geneva who aim to enter Switzerland's growing tech sector. Through hands-on practice and the development of concrete skills, participants gain the confidence and independence they need to thrive in the digital world.",
    "aboutPage.problem.title": "Problem Statement",
    "aboutPage.problem.text": "Despite Switzerland's strong digital economy, many qualified women face barriers to entering the technology workforce. These barriers include limited professional networks, lack of recognized tech experience, and insufficient access to practical digital training aligned with the job market. In Geneva, many women possess valuable education and work experience but struggle to transition into digital careers.",
    "aboutPage.solution.title": "Our Solution",
    "aboutPage.solution.text": "Ellatech provides an accessible and guided pathway for women to build digital skills and confidence through:",
    "aboutPage.solution.point1": "An AI-powered onboarding platform that analyzes participants' skills, background, and interests",
    "aboutPage.solution.point2": "A structured 3-month digital career pathway",
    "aboutPage.solution.point3": "Specialization tracks including Web & App Development, Data Analysis, AI & Digital Skills",
    "aboutPage.solution.point4": "Mentorship, peer learning, and networking opportunities",
    "aboutPage.solution.point5": "Career preparation aligned with Swiss hiring practices",
    "aboutPage.solution.closing": "This approach allows participants to follow a personalized learning journey that matches their strengths and career goals.",
    "aboutPage.target.title": "Target Participants",
    "aboutPage.target.text": "The program supports women living in Geneva who are interested in transitioning into digital careers but lack access to structured pathways or professional networks.",
    "aboutPage.target.cta": "Check Eligibility & Apply",
  },
  fr: {
    // Nav
    "nav.about": "À Propos",
    "nav.program": "Programme",
    "nav.benefits": "Avantages",
    "nav.eligibility": "Éligibilité",
    "nav.timeline": "Calendrier",
    "nav.partners": "Partenaires",
    "nav.apply": "Postuler",

    // Hero
    "hero.title": "Carrières Tech du Futur pour les Femmes",
    "hero.subtitle": "Une initiative de transition de carrière et de montée en compétences numériques pour accompagner les femmes à Genève vers le secteur tech suisse — en pratiquant et développant des compétences concrètes pour devenir autonomes dans le monde numérique.",
    "hero.cta1": "Postuler Maintenant",
    "hero.cta2": "En Savoir Plus",

    // About
    "about.tag": "À Propos du Programme",
    "about.title": "Des Carrières Durables pour l'Avenir",
    "about.description": "Ellatech est une initiative de transition de carrière et de montée en compétences numériques conçue pour accompagner les femmes à Genève qui souhaitent intégrer le secteur tech suisse — en pratiquant et développant des compétences concrètes pour devenir autonomes dans le monde numérique.",
    "about.mission.title": "Notre Mission",
    "about.mission.text": "Malgré la forte économie numérique de la Suisse, de nombreuses femmes qualifiées issues de l'immigration font face à des obstacles structurels. Nous comblons ce fossé par une formation numérique accessible combinée à une préparation à l'employabilité.",
    "about.who.title": "Pour Qui ?",
    "about.who.text": "Femmes vivant à Genève qui souhaitent se reconvertir dans la tech. Aucune expérience préalable requise — juste de la motivation et un accès numérique de base.",
    "about.gain.title": "Ce Que Vous Gagnerez",
    "about.gain.text": "Des compétences numériques adaptées au marché, un mentorat professionnel, un accompagnement carrière adapté aux standards suisses, et un accès à l'écosystème tech genevois.",

    // Program
    "program.tag": "Aperçu du Programme",
    "program.title": "Votre Parcours de 3 Mois",
    "program.month1.title": "Mois 1",
    "program.month1.name": "Fondamentaux Numériques",
    "program.month1.desc": "Développez votre culture numérique, explorez les métiers tech et recevez votre évaluation personnalisée par IA.",
    "program.month2.title": "Mois 2",
    "program.month2.name": "Compétences Techniques",
    "program.month2.desc": "Formation pratique en développement Web & Mobile, analyse de données ou IA & compétences numériques.",
    "program.month3.title": "Mois 3",
    "program.month3.name": "Préparation Carrière",
    "program.month3.desc": "Perfectionnez votre CV, construisez votre portfolio, préparez vos entretiens et connectez-vous avec les employeurs tech suisses.",

    // Benefits
    "benefits.tag": "Ce Que Vous Recevez",
    "benefits.title": "Tout Pour Réussir",
    "benefits.ai": "Évaluation IA",
    "benefits.ai.desc": "Évaluation personnalisée de vos compétences et intérêts pour créer un parcours d'apprentissage sur mesure.",
    "benefits.training": "Formation Structurée",
    "benefits.training.desc": "12 semaines de formation guidée et pratique dans les domaines numériques les plus demandés.",
    "benefits.mentorship": "Programme de Mentorat",
    "benefits.mentorship.desc": "Connectez-vous avec des femmes expérimentées dans la tech qui guideront votre transition.",
    "benefits.career": "Accompagnement Carrière",
    "benefits.career.desc": "Création de CV, préparation aux entretiens et stratégies adaptées au marché suisse.",
    "benefits.ecosystem": "Accès à l'Écosystème Tech",
    "benefits.ecosystem.desc": "Introductions aux entreprises tech suisses, événements de networking et opportunités de stages.",
    "benefits.community": "Communauté de Pairs",
    "benefits.community.desc": "Rejoignez une communauté solidaire de femmes en transition — apprenez, grandissez et réussissez ensemble.",

    // Eligibility
    "eligibility.tag": "Critères d'Éligibilité",
    "eligibility.title": "Qui Peut Postuler ?",
    "eligibility.subtitle": "Notre programme s'adresse aux femmes qui répondent aux critères suivants :",
    "eligibility.1": "Résider dans le Canton de Genève",
    "eligibility.2": "S'identifier comme femme",
    "eligibility.3": "Être motivée à se reconvertir dans une carrière tech",
    "eligibility.4": "Avoir un accès numérique de base (ordinateur & internet)",
    "eligibility.5": "Être motivée pour poursuivre une carrière dans la tech",
    "eligibility.cta": "Vérifier Votre Éligibilité & Postuler",

    // Timeline
    "timeline.tag": "Calendrier du Programme",
    "timeline.title": "Dates Clés",
    "timeline.1.date": "Mai 2026",
    "timeline.1.title": "Ouverture des Candidatures",
    "timeline.1.desc": "Soumettez votre candidature et complétez l'évaluation initiale.",
    "timeline.2.date": "Juin 2026",
    "timeline.2.title": "Début de la Cohorte",
    "timeline.2.desc": "Accueil, orientation et évaluation des compétences par IA.",
    "timeline.3.date": "Juin – Août 2026",
    "timeline.3.title": "Durée du Programme",
    "timeline.3.desc": "12 semaines de formation intensive et de préparation professionnelle.",
    "timeline.4.date": "Septembre 2026",
    "timeline.4.title": "Diplôme & Lancement de Carrière",
    "timeline.4.desc": "Présentez vos projets, connectez-vous avec les employeurs et lancez votre carrière.",

    // Partners
    "partners.tag": "Partenaires & Soutiens",
    "partners.title": "Construire Ensemble",
    "partners.subtitle": "Ellatech est rendu possible grâce à des partenariats avec des organisations locales, des entreprises tech et des institutions de formation engagées pour l'inclusion et la diversité.",
    "partners.ngos": "ONG Locales",
    "partners.ngos.desc": "Organisations communautaires soutenant l'intégration et l'inclusion sociale à Genève.",
    "partners.tech": "Entreprises Tech",
    "partners.tech.desc": "Entreprises tech suisses de premier plan offrant mentorat, stages et perspectives de carrière.",
    "partners.training": "Partenaires de Formation",
    "partners.training.desc": "Institutions éducatives offrant un soutien pédagogique et des certifications.",
    "partners.cta": "Devenir Partenaire",

    // Partner Form Page
    "partner.back": "Retour aux Partenaires",
    "partner.tag": "Partenariat",
    "partner.title": "Devenir Partenaire",
    "partner.subtitle": "Rejoignez-nous pour accompagner les femmes à Genève vers des carrières tech durables. Que vous soyez une entreprise, ONG ou association locale, votre soutien fait la différence.",
    "partner.form.orgInfo": "Informations sur l'Organisation",
    "partner.form.orgName": "Nom de l'Organisation",
    "partner.form.orgNamePlaceholder": "Nom de votre organisation",
    "partner.form.website": "Site Web",
    "partner.form.orgType": "Type d'Organisation",
    "partner.form.orgType.company": "Entreprise",
    "partner.form.orgType.ngo": "ONG",
    "partner.form.orgType.association": "Association",
    "partner.form.orgType.academic": "Académique",
    "partner.form.orgType.government": "Gouvernement",
    "partner.form.orgType.other": "Autre",
    "partner.form.contactInfo": "Personne de Contact",
    "partner.form.contactName": "Nom Complet",
    "partner.form.contactNamePlaceholder": "Nom de la personne de contact",
    "partner.form.contactRole": "Rôle / Poste",
    "partner.form.contactRolePlaceholder": "ex. Responsable RH",
    "partner.form.email": "Email",
    "partner.form.emailPlaceholder": "contact@organisation.ch",
    "partner.form.phone": "Téléphone",
    "partner.form.partnershipInterest": "Intérêt de Partenariat",
    "partner.form.partnershipType": "Comment souhaitez-vous contribuer ?",
    "partner.form.type.mentorship": "Mentorat",
    "partner.form.type.internship": "Stages",
    "partner.form.type.training": "Soutien à la Formation",
    "partner.form.type.funding": "Financement / Sponsoring",
    "partner.form.message": "Message Complémentaire",
    "partner.form.messagePlaceholder": "Parlez-nous de votre organisation et de la manière dont vous souhaitez collaborer...",
    "partner.form.terms": "J'accepte d'être contacté(e) par Ellatech concernant cette demande de partenariat.",
    "partner.form.submit": "Soumettre la Demande",
    "partner.form.submitting": "Envoi en cours...",
    "partner.form.success": "Demande Envoyée !",
    "partner.form.successDesc": "Merci pour votre intérêt. Nous vous contacterons bientôt.",

    // Footer
    "footer.tagline": "Nous ne formons pas seulement. Nous créons des avenirs professionnels durables.",
    "footer.program": "Programme",
    "footer.connect": "Contact",
    "footer.legal": "Légal",
    "footer.privacy": "Politique de Confidentialité",
    "footer.terms": "Conditions d'Utilisation",
    "footer.rights": "Tous droits réservés.",

    // Apply Now Page
    "apply.back": "Retour à l'accueil",
    "apply.tag": "Candidature",
    "apply.title": "Postuler au Programme",
    "apply.subtitle": "Faites le premier pas vers votre carrière tech. Remplissez le formulaire ci-dessous et nous vous recontacterons.",
    "apply.form.personalInfo": "Informations Personnelles",
    "apply.form.fullName": "Nom Complet",
    "apply.form.fullNamePlaceholder": "Votre nom complet",
    "apply.form.email": "Email",
    "apply.form.emailPlaceholder": "votre.email@exemple.com",
    "apply.form.phone": "Téléphone",
    "apply.form.nationality": "Nationalité",
    "apply.form.nationalityPlaceholder": "ex. Syrienne, Érythréenne, Colombienne",
    "apply.form.residenceStatus": "Statut de Résidence en Suisse",
    "apply.form.residenceStatusPlaceholder": "ex. Permis B, Permis F, Demandeur d'asile",
    "apply.form.background": "Parcours & Expérience",
    "apply.form.education": "Niveau d'Éducation",
    "apply.form.education.high_school": "Lycée",
    "apply.form.education.bachelor": "Licence",
    "apply.form.education.master": "Master ou Plus",
    "apply.form.education.other": "Autre",
    "apply.form.experience": "Expérience Professionnelle",
    "apply.form.experiencePlaceholder": "Décrivez brièvement votre expérience professionnelle...",
    "apply.form.techInterest": "Votre Intérêt pour la Tech",
    "apply.form.techTrack": "Quel parcours vous intéresse le plus ?",
    "apply.form.tech.webdev": "Développement Web & App",
    "apply.form.tech.data": "Analyse de Données",
    "apply.form.tech.ai": "IA & Compétences Numériques",
    "apply.form.tech.unsure": "Pas Encore Sûre",
    "apply.form.motivation": "Pourquoi souhaitez-vous rejoindre ?",
    "apply.form.motivationPlaceholder": "Parlez-nous de vos objectifs et pourquoi ce programme vous convient...",
    "apply.form.terms": "Je confirme remplir les critères d'éligibilité et j'accepte d'être contactée par Ellatech.",
    "apply.form.submit": "Soumettre la Candidature",
    "apply.form.submitting": "Envoi en cours...",
    "apply.form.success": "Candidature Envoyée !",
    "apply.form.successDesc": "Merci pour votre candidature. Nous l'examinerons et vous recontacterons bientôt.",

    // Impact
    "impact.title": "Notre Impact",
    "impact.members": "Participantes",
    "impact.mentors": "Mentors",
    "impact.events": "Événements",
    "impact.partners": "Partenaires",

    // About Page
    "aboutPage.tag": "À Propos de Ellatech",
    "aboutPage.title": "Autonomiser les Femmes vers des Carrières Tech",
    "aboutPage.subtitle": "Un hub de transition de carrière numérique accompagnant les femmes à Genève vers le secteur technologique.",
    "aboutPage.overview.title": "Aperçu",
    "aboutPage.overview.text": "Ellatech est une initiative de transition de carrière et de montée en compétences numériques conçue pour accompagner les femmes à Genève qui souhaitent intégrer le secteur tech suisse en pleine croissance. Grâce à une pratique concrète et au développement de compétences tangibles, les participantes acquièrent la confiance et l'autonomie nécessaires pour s'épanouir dans le monde numérique.",
    "aboutPage.problem.title": "Problématique",
    "aboutPage.problem.text": "Malgré la forte économie numérique de la Suisse, de nombreuses femmes qualifiées font face à des obstacles pour intégrer le marché du travail technologique. Ces obstacles incluent des réseaux professionnels limités, un manque d'expérience reconnue dans la tech, et un accès insuffisant à une formation numérique pratique alignée sur le marché de l'emploi. À Genève, de nombreuses femmes possèdent une éducation et une expérience professionnelle précieuses mais peinent à se reconvertir dans les carrières numériques.",
    "aboutPage.solution.title": "Notre Solution",
    "aboutPage.solution.text": "Ellatech offre un parcours accessible et guidé pour que les femmes développent leurs compétences numériques et leur confiance à travers :",
    "aboutPage.solution.point1": "Une plateforme d'intégration alimentée par l'IA qui analyse les compétences, le parcours et les intérêts des participantes",
    "aboutPage.solution.point2": "Un parcours de carrière numérique structuré de 3 mois",
    "aboutPage.solution.point3": "Des spécialisations incluant Développement Web & App, Analyse de Données, IA & Compétences Numériques",
    "aboutPage.solution.point4": "Mentorat, apprentissage entre pairs et opportunités de networking",
    "aboutPage.solution.point5": "Préparation de carrière alignée sur les pratiques de recrutement suisses",
    "aboutPage.solution.closing": "Cette approche permet aux participantes de suivre un parcours d'apprentissage personnalisé qui correspond à leurs forces et objectifs de carrière.",
    "aboutPage.target.title": "Participantes Cibles",
    "aboutPage.target.text": "Le programme soutient les femmes vivant à Genève qui souhaitent se reconvertir dans les carrières numériques mais n'ont pas accès à des parcours structurés ou des réseaux professionnels.",
    "aboutPage.target.cta": "Vérifier l'Éligibilité & Postuler",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
